---
repos:
  - repo: https://github.com/thlorenz/doctoc
    rev: v2.4.1
    hooks:
      - id: doctoc
        args: ["--update-only"]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.48.0
    hooks:
      - id: markdownlint-fix
        args: ["--ignore", "LICENSE.md", "--disable", "~MD013"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: forbid-submodules
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      - id: ruff-check
        args: ["--fix", "--ignore=E402"]
        types_or: [ python, pyi, jupyter ]
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
